export const Paras = [
    {
      number: 1,
      arabic: "الم",
      transliterated: "Alif Lam Meem",
      downloadLink: "/quranPak/parah-1.pdf",
    },
    {
      number: 2,
      arabic: "سیقول",
      transliterated: "Sayaqool",
      downloadLink: "/quranPak/parah-2.pdf",
    },
    {
      number: 3,
      arabic: "تلك الرسل",
      transliterated: "Tilkal Rusull",
      downloadLink: "/quranPak/parah-3.pdf",
    },
    {
      number: 4,
      arabic: "لن تنالوا",
      transliterated: "Lan Tana Loo",
      downloadLink: "/quranPak/parah-4.pdf",
    },
    {
      number: 5,
      arabic: "والمحصنت",
      transliterated: "Wal Mohsanat",
      downloadLink: "/quranPak/parah-5.pdf",
    },
    {
      number: 6,
      arabic: "لا یحب الله",
      transliterated: "La Yuhibbullah",
      downloadLink: "/quranPak/parah-6.pdf",
    },
    {
      number: 7,
      arabic: "واذا سمعوا",
      transliterated: "Wa Iza Samiu",
      downloadLink: "/quranPak/parah-7.pdf",
    },
    {
      number: 8,
      arabic: "ولو اننا",
      transliterated: "Wa Lau Annana",
      downloadLink: "/quranPak/parah-8.pdf",
    },
    {
      number: 9,
      arabic: "قال الملاء",
      transliterated: "Qalal Malao",
      downloadLink: "/quranPak/parah-9.pdf",
    },
    {
      number: 10,
      arabic: "واعلموا",
      transliterated: "Wa A'lamu",
      downloadLink: "/quranPak/parah-10.pdf",
    },
    {
      number: 11,
      arabic: "يعتذرون",
      transliterated: "Yatazeroon",
      downloadLink: "/quranPak/parah-11.pdf",
    },
    {
      number: 12,
      arabic: "و ما من دابة",
      transliterated: "Wa Mamin Da'bat",
      downloadLink: "/quranPak/parah-12.pdf",
    },
    {
      number: 13,
      arabic: "وما ابرئ",
      transliterated: "Wa Ma Ubrio",
      downloadLink: "/quranPak/parah-13.pdf",
    },
    { number: 14, arabic: "ربما", transliterated: "Rubama", downloadLink: "/quranPak/parah-14.pdf" },
    {
      number: 15,
      arabic: "سبحان الذي",
      transliterated: "Subhanallazi",
      downloadLink: "/quranPak/parah-15.pdf",
    },
    {
      number: 16,
      arabic: "قال الم",
      transliterated: "Qal Alam",
      downloadLink: "/quranPak/parah-16.pdf",
    },
    {
      number: 17,
      arabic: "اقتربت",
      transliterated: "Aqtarabo",
      downloadLink: "/quranPak/parah-17.pdf",
    },
    {
      number: 18,
      arabic: "قد افلح",
      transliterated: "Qadd Aflaha",
      downloadLink: "/quranPak/parah-18.pdf",
    },
    {
      number: 19,
      arabic: "وقال الذين",
      transliterated: "Wa Qalallazina",
      downloadLink: "/quranPak/parah-19.pdf",
    },
    {
      number: 20,
      arabic: "امن خلق",
      transliterated: "A'man Khalaq",
      downloadLink: "/quranPak/parah-20.pdf",
    },
    {
      number: 21,
      arabic: "اتل ما اوحي",
      transliterated: "Utlu Ma Oohi",
      downloadLink: "/quranPak/parah-21.pdf",
    },
    {
      number: 22,
      arabic: "و ما ينفع",
      transliterated: "Wa Manyaqnut",
      downloadLink: "/quranPak/parah-22.pdf",
    },
    {
      number: 23,
      arabic: "و ما لي",
      transliterated: "Wa Mali",
      downloadLink: "/quranPak/parah-23.pdf",
    },
    {
      number: 24,
      arabic: "فمن اظلم",
      transliterated: "Faman Azlam",
      downloadLink: "/quranPak/parah-24.pdf",
    },
    {
      number: 25,
      arabic: "اليه يرد",
      transliterated: "Elahe Yuruddo",
      downloadLink: "/quranPak/parah-25.pdf",
    },
    {
      number: 26,
      arabic: "حم",
      transliterated: "Ha'a Meem",
      downloadLink: "/quranPak/parah-27.pdf",
    },
    {
      number: 27,
      arabic: "قال فما خطبكم",
      transliterated: "Qala Fama Khatbukum",
      downloadLink: "/quranPak/parah-27.pdf",
    },
    {
      number: 28,
      arabic: "قد سمع الله",
      transliterated: "Qadd Sami Allah",
      downloadLink: "/quranPak/parah-28.pdf",
    },
    {
      number: 29,
      arabic: "تبارك الذي",
      transliterated: "Tabarakallazi",
      downloadLink: "/quranPak/parah-29.pdf",
    },
    {
      number: 30,
      arabic: "عم يتساءلون",
      transliterated: "Amma Yatasa'loon",
      downloadLink: "30",
    },

  ];
